/** Legacy and retired content routes → landing folio, FAQ, or brief form */
export const SEO_SLUG_REDIRECTS: Record<string, string> = {
  "/contact": "/send-brief",
  "/how-to-instruct": "/#process",
  "/guides": "/faq",
  "/guides/ahmadi-asylum-pakistan": "/faq",
  "/guides/ahmadi-asylum-pakistan-guide": "/faq",
  "/guides/blasphemy-pakistan-guide": "/faq",
  "/guides/blasphemy-pakistan-expert-guide": "/faq",
  "/guides/honour-based-violence": "/faq",
  "/guides/honour-based-violence-pakistan": "/faq",
  "/guides/pakistan-political-asylum": "/faq",
  "/guides/pakistan-political-asylum-guide": "/faq",
  "/guides/pakistan-cpin-guide": "/#cpin",
  "/guides/instructing-pakistan-expert": "/#process",
  "/asylum-profiles": "/#profiles",
  "/asylum-profiles/ahmadi-muslims": "/#profiles",
  "/asylum-profiles/ahmadi-muslims-pakistan": "/#profiles",
  "/asylum-profiles/blasphemy": "/#profiles",
  "/asylum-profiles/blasphemy-accusations-pakistan": "/#profiles",
  "/asylum-profiles/women-hbv": "/#profiles",
  "/asylum-profiles/women-honour-based-violence": "/#profiles",
  "/asylum-profiles/lgbtq-pakistan": "/#profiles",
  "/asylum-profiles/lgbtq-asylum-pakistan": "/#profiles",
  "/asylum-profiles/political-persecution": "/#profiles",
  "/asylum-profiles/political-persecution-pakistan": "/#profiles",
  "/asylum-profiles/shia-muslims-pakistan": "/#profiles",
  "/asylum-profiles/christians-religious-minorities": "/#profiles",
  "/asylum-profiles/actors-of-protection-pakistan": "/#profiles",
  "/case-types": "/#process",
  "/case-types/asylum-appeal-ftt": "/#process",
  "/case-types/upper-tribunal-pakistan": "/#process",
  "/case-types/ahmadi-asylum-claims": "/#profiles",
  "/case-types/blasphemy-asylum": "/#profiles",
  "/case-types/blasphemy-asylum-pakistan": "/#profiles",
  "/case-types/hbv-pakistan": "/#profiles",
  "/case-types/honour-based-violence-pakistan": "/#profiles",
  "/case-types/deportation-removal-pakistan": "/#process",
  "/case-types/fresh-claims-pakistan": "/#process",
  "/case-types/political-claim": "/#profiles",
  "/case-types/political-claim-pakistan": "/#profiles",
  "/services": "/#reports",
  "/services/country-condition-reports": "/#reports",
  "/services/ahmadi-asylum-reports": "/#reports",
  "/services/blasphemy-expert-reports": "/#reports",
  "/services/honour-based-violence-reports": "/#reports",
  "/services/lgbtq-asylum-reports": "/#reports",
  "/services/lgbtq-asylum-pakistan": "/#reports",
  "/services/political-persecution-reports": "/#reports",
  "/services/cpin-challenge-reports": "/#cpin",
  "/services/cpin-challenge": "/#cpin",
  "/services/expert-oral-evidence": "/#reports",
  "/services/oral-evidence": "/#reports",
  "/cpin-country-guidance": "/#cpin",
  "/qualifications": "/#evidence",
  "/glossary": "/faq",
  "/what-is-a-pakistan-expert-report": "/",
  "/what-is-a-pakistan-expert-witness": "/",
  "/fees": "/#process",
  "/experts": "/#evidence",
};

const PREFIX_REDIRECTS: { prefix: string; to: string }[] = [
  { prefix: "/asylum-profiles/", to: "/#profiles" },
  { prefix: "/case-types/", to: "/#process" },
  { prefix: "/services/", to: "/#reports" },
  { prefix: "/guides/", to: "/faq" },
];

export function resolveLegacyRedirect(pathname: string): string | undefined {
  if (SEO_SLUG_REDIRECTS[pathname]) return SEO_SLUG_REDIRECTS[pathname];
  for (const { prefix, to } of PREFIX_REDIRECTS) {
    if (pathname.startsWith(prefix)) return to;
  }
  return undefined;
}
